using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Web.UI;
using System.Resources;

// 組件的一般資訊是由下列的屬性集控制。
// 變更這些屬性的值即可修改組件的相關
// 資訊。
[assembly: AssemblyTitle("Custom web server controls")]
[assembly: AssemblyDescription("開發網站統一專用自訂伺服器控制項")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("WebCustomControls")]
[assembly: AssemblyCopyright("Copyright © Developed by Leon")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: TagPrefix("APTemplate", "wcc")]

// 將 ComVisible 設定為 false 會使得這個組件中的型別
// 對 COM 元件而言為不可見。如果您需要從 COM 存取這個組件中
// 的型別，請在該型別上將 ComVisible 屬性設定為 true。
[assembly: ComVisible(false)]

// 下列 GUID 為專案公開 (Expose) 至 COM 時所要使用的 typelib ID
[assembly: Guid("bdb49f2b-ec99-4b51-be41-2f5580919a76")]

// 組件的版本資訊是由下列四項值構成:
//
//      主要版本
//      次要版本 
//      組建編號
//      修訂編號
//
// 您可以指定所有的值，也可以依照以下的方式，使用 '*' 將組建和修訂編號
// 指定為預設值:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: NeutralResourcesLanguageAttribute("")]

[assembly: WebResource("APTemplate.Resources.ControlJS.calendar.js", "application/x-javascript", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.ControlJS.popcalendar.js", "application/x-javascript", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.ControlJS.chtpopcalendar.js", "application/x-javascript", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.ControlJS.progressbar.js", "application/x-javascript", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.ControlJS.TabsView.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.Menu.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.WebScript.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.WebUIValidation.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.coordinates.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.core.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.css.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.drag.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.events.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.ControlJS.AjaxUpload.js", "application/x-javascript")]
[assembly: WebResource("APTemplate.Resources.calendar1.htm", "text/html", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.calendar2.htm", "text/html")]
[assembly: WebResource("APTemplate.Resources.button_01.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.button_02.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.button_03.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.firstPage.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.firstPageDisabled.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.icon-ffwd.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.icon-frew.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.icon-fwd.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.icon-rew.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.lastPage.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.lastPageDisabled.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.nextPage.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.nextPageDisabled.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.prevPage.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.prevPageDisabled.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.rowsDisplayed.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.scrollbutton_down.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.separator.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.calendar.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.SmallCalendar.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.toolbarempty.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.arrow_down.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.arrow_right.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample3_main_arrow.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample3_sub_arrow.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.arrow_sub.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.light_arrow_down.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.medium_purple_right.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample2_bg.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample2_main_arrow.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample2_sub_arrow.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample13_main_bg.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample13_sub_expand_default.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample13_sub_expand_on.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.small_red_pointer.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.arrows_0.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.beige_rounded_bc.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.beige_rounded_bl.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.beige_rounded_br.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample1_main_arrow.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.sample1_sub_arrow.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.tree_main_plus.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.tree_main_plus_active.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.tree_main_plus_hover.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.tree_sub_plus.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.tree_sub_plus_active.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.tree_sub_plus_hover.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.calendar.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.close.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.left1.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.left2.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.right1.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.right2.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.drop1.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.drop2.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.refresh.jpg", "image/jpeg")]
[assembly: WebResource("APTemplate.Resources.refresh.png", "image/jpeg")]
[assembly: WebResource("APTemplate.Resources.progressbar.gif", "image/gif")]

//Register HtmlEditor Control javascript files
//[assembly: WebResource("APTemplate.Resources.HtmlEditor.HTMLPage1.htm", "text/html", PerformSubstitution = true)]
//[assembly: WebResource("APTemplate.Resources.HtmlEditor.HTMLPage1.htm", "text/html", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.js.RichText.js", "text/javascript")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.js.Encoder.js", "text/javascript")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.js.jscolor.js", "text/javascript")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.js.slider.js", "text/javascript")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.js.Initializer.js", "text/javascript")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.js.loading.js", "text/javascript")]


//Register HtmlEditor Control stylesheet Files
[assembly: WebResource("APTemplate.Resources.HtmlEditor.EditorStyles.slider.css", "text/css")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.EditorStyles.Style.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.EditorStyles.textEditor.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.EditorStyles.loading.css", "text/css")]

//Register HtmlEditor Control pictures -->ColorPicker
[assembly: WebResource("APTemplate.Resources.HtmlEditor.ColorPicker.colormap.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.ColorPicker.palette.jpg", "image/jpg")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.ColorPicker.palette.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.character_set.png", "image/png")]

//Register HtmlEditor Control pictures -->TextEditor
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.cut.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.1280657916_format-text-italic.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_bold.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_bold_on.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.swf.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.swfBackground.png.png", "image/png")]

[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.bullets.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.loadign.gif", "image/gif")]

[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.subscript.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.superscript.png", "image/png")]

[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.bullets_RTL.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.center.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.colorPicker.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.copy.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.createtable.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.cut.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.directionLeft.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.editorMode.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.eraser.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.font_bold.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.fontFamily.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.fontFamily2.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.fontFamily3.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.fontsize.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.fontStyle.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.fontStyle2.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.format_justify_left.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.format_justify_right.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.highlight.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.highlighter_text.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.HorizontalLine.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.Htmlsource.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.indent.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_button.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_checkbox.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_combobox.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_fileUpload.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_image.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_listBox.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_password.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_textarea.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insert_textbox.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.insertImage.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.italic.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.italic2.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.link2.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.link3.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.ltr.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.ltr_direction.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.ltr_direction_on.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_list_numbers.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_list_numbers-RTL.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.outdent.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.page_break.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.link_break.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.paste.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.preview.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.print.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.printer.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.redo.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.resize_both.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.resize_horizontal.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.resize_vertical.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.rtl.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.rtl_direction.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.rtl_direction_on.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.save.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.save_as.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.select_all.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.source.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_strikethrough.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.table.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_align_center.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_italic.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_italic_on.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.text_underline.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.textColor.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.textColor2.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.underline.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.underline_on.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.undo.png", "image/png")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.colormap.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.palette.gif", "image/gif")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.palette.jpg", "image/jpg")]
[assembly: WebResource("APTemplate.Resources.HtmlEditor.RichTextBoxIcons.ui_radio_button.png", "image/png")]