//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTemplate.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Bounce_Arrows {
            get {
                return ResourceManager.GetString("Basic_Bounce_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        /////set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ////*[end data]*/}
        ///
        ///
        ///
        /////[IM Code]
        ///
        ///
        ///// ---- Add-On [3.8 KB]: Expander Icon Animations ----
        ///function imenus_expandani_init(obj,dt [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Bounce_Arrows_Horizontal {
            get {
                return ResourceManager.GetString("Basic_Bounce_Arrows_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1() {
        ///
        ///
        ///    this.menu_showhide_delay = 150
        ///    this.show_subs_onclick = false
        ///    this.hide_focus_box = false
        ///
        ///
        ///    //set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///    this.box_animation_type = &quot;pointer&quot;
        ///
        ///    this.box_animation_frames = 18
        ///    this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///    /*[end data]*/
        ///}
        ///
        ///
        ///
        /////[IM Code]
        ///
        ///
        ///// ---- Add-On [3.8 KB]: Expander Icon Animations ----
        ///function [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Bounce_Arrows_Vertical {
            get {
                return ResourceManager.GetString("Basic_Bounce_Arrows_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///
        ///   /*---------------------------------------------
        ///   Box Animation Settings
        ///   ---------------------------------------------*/
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;center&quot;
        ///
        ///	this.box_animation_frames = 15
        ///	this.box_animation_styles = &quot;border-style:solid; border-color:#999999; border-width:1px; &quot;
        ///
        ///
        ///
        ///   /*------------------ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Horizontal {
            get {
                return ResourceManager.GetString("Basic_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Red_Highlight {
            get {
                return ResourceManager.GetString("Basic_Red_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///
        ///   /*---------------------------------------------
        ///   Box Animation Settings
        ///   ---------------------------------------------*/
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:solid; border-color:#ff0000; border-width:1px 0p [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Red_Highlight_Horizontal {
            get {
                return ResourceManager.GetString("Basic_Red_Highlight_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///
        ///   /*---------------------------------------------
        ///   Box Animation Settings
        ///   ---------------------------------------------*/
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:solid; border-color:#ff0000; border-width:1px 0px; &quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Red_Highlight_Vertical {
            get {
                return ResourceManager.GetString("Basic_Red_Highlight_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///
        ///   /*---------------------------------------------
        ///   Box Animation Settings
        ///   ---------------------------------------------*/
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;center&quot;
        ///
        ///	this.box_animation_frames = 15
        ///	this.box_animation_styles = &quot;border-style:solid; border-color:#999999; border-width:1px; &quot;
        ///
        ///
        ///
        ///   /*-------------------- [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Basic_Vertical {
            get {
                return ResourceManager.GetString("Basic_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Blue_Tones {
            get {
                return ResourceManager.GetString("Blue_Tones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Blue_Tones_Horizontal {
            get {
                return ResourceManager.GetString("Blue_Tones_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/
        ///
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Blue_Tones_Vertical {
            get {
                return ResourceManager.GetString("Blue_Tones_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Basic]
        ///.imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibilit [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Drop_Shadow {
            get {
                return ResourceManager.GetString("Drop_Shadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///
        ///   /*---------------------------------------------
        ///   Box Animation Settings
        ///   ---------------------------------------------*/
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;center&quot;
        ///
        ///	this.box_animation_frames = 10
        ///	this.box_animation_styles = &quot;border-style:solid; border-color:#bbbbbb; border-width:1px; &quot;
        ///
        ///
        ///
        ///
        ///   /*---------------- [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Drop_Shadow_Horizontal {
            get {
                return ResourceManager.GetString("Drop_Shadow_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;center&quot;
        ///
        ///	this.box_animation_frames = 10
        ///	this.box_animation_styles = &quot;border-style:solid; border-color:#bbbbbb; border-width:1px; &quot;
        ///
        ///
        ///	this.subs_ie_transition_show = &quot;&quot;
        ///
        ///
        ///
        ////*[end data]*/}
        ///
        ///
        ///// ---- Add-On [3.2 KB]: Box Outline Animations ----
        ///;function imenus_box_ani_init(obj,dto){var tid=ob [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Drop_Shadow_Vertical {
            get {
                return ResourceManager.GetString("Drop_Shadow_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Gradient_Background {
            get {
                return ResourceManager.GetString("Gradient_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Gradient_Background_Horizontal {
            get {
                return ResourceManager.GetString("Gradient_Background_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/
        ///
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Gradient_Background_Vertical {
            get {
                return ResourceManager.GetString("Gradient_Background_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Gray_Scale {
            get {
                return ResourceManager.GetString("Gray_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Gray_Scale_Horizontal {
            get {
                return ResourceManager.GetString("Gray_Scale_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/
        ///
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Gray_Scale_Vertical {
            get {
                return ResourceManager.GetString("Gray_Scale_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Basic]
        ///&lt;table style=&apos;display: inline;vertical-align:top;&apos;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;
        ///      &lt;div class=&apos;imrcmain0 imgl&apos; style=&apos;width: &lt;#MenuWidth#&gt;px; z-index: 999999; position: relative;&apos;&gt;
        ///        &lt;div class=&apos;imcm imde&apos; id=&apos;imouter1&apos;&gt;
        ///          &lt;ul id=&apos;imenus1&apos;&gt;
        ///            &lt;li class=&apos;imatm&apos; style=&apos;width: &lt;#MenuItemWidth#&gt;px; background-color: #&lt;#MainItem_BgColor#&gt;;&apos;&gt;
        ///              &lt;a href=&apos;#&apos; style=&apos;color: #&lt;#MainItem_ForeColor#&gt;;&apos;&gt;&lt;span class=&apos;imea imeam&apos; style=&apos;background-image: url(&lt;#UrlPath#&gt;/sample3_ma [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Stretch_Buttons_Tan {
            get {
                return ResourceManager.GetString("Stretch_Buttons_Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///
        ///   /*---------------------------------------------
        ///   Main Menu Graphic Buttons
        ///   ---------------------------------------------*/
        ///
        ///
        ///	this.gb_cap_width = &quot;6&quot;
        ///	this.gb_cap_height = &quot;22&quot;
        ///
        ///	this.gb_left_cap = &apos;&lt;#UrlPath#&gt;ControlImages/beige_rounded_bl.gif&apos;;
        ///	this.gb_center_tile = &apos;&lt;#UrlPath#&gt;ControlImages/beige_rounded_bc.gif&apos;;
        ///	this.gb_right_cap = &apos;&lt;#UrlPath#&gt;ControlI [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Stretch_Buttons_Tan_Horizontal {
            get {
                return ResourceManager.GetString("Stretch_Buttons_Tan_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///
        ///   /*---------------------------------------------
        ///   Main Menu Graphic Buttons
        ///   ---------------------------------------------*/
        ///
        ///
        ///	this.gb_cap_width = &quot;6&quot;
        ///	this.gb_cap_height = &quot;22&quot;
        ///
        ///	this.gb_left_cap = &apos;&lt;#UrlPath#&gt;ControlImages/beige_rounded_bl.gif&apos;;
        ///	this.gb_center_tile = &apos;&lt;#UrlPath#&gt;ControlImages/beige_rounded_bc.gif&apos;;
        ///	this.gb_right_cap = &apos;&lt;#UrlPath#&gt;ControlImage [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Stretch_Buttons_Tan_Vertical {
            get {
                return ResourceManager.GetString("Stretch_Buttons_Tan_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 .imcm ul,.imcm li,.imcm div,.imcm span,.imcm a{text-align:left;vertical-align:top;padding:0px;margin:0;list-style:none outside none;border-style:none;background-image:none;clear:none;float:none;display:block;position:static;overflow:visible;line-height:normal;}.imcm li a img{display:inline;border-width:0px;}.imcm span{display:inline;}.imcm .imclear,.imclear{clear:both;height:0px;visibility:hidden;line-height:0px;font-size:1px;}.imcm .imsc{position:relative;}.imcm .imsubc{position:absolute;visibility:hidden; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Thick_Borders {
            get {
                return ResourceManager.GetString("Thick_Borders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///function imenus_data1(){
        ///
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Thick_Borders_Horizontal {
            get {
                return ResourceManager.GetString("Thick_Borders_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 function imenus_data1(){
        ///
        ///	this.menu_showhide_delay = 150
        ///	this.show_subs_onclick = false
        ///	this.hide_focus_box = false
        ///
        ///	//set to... &quot;pointer&quot;, &quot;center&quot;, &quot;top&quot;, &quot;left&quot;
        ///	this.box_animation_type = &quot;pointer&quot;
        ///
        ///	this.box_animation_frames = 18
        ///	this.box_animation_styles = &quot;background-color:transparent; border-style:none; border-color:#ff0000; border-width:1px 0px; &quot;
        ///
        ///
        ///   /*---------------------------------------------
        ///   IE Transition Effects
        ///   ---------------------------------------------*/
        ///
        ///
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Thick_Borders_Vertical {
            get {
                return ResourceManager.GetString("Thick_Borders_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /*!!!!!!!!!!! Add-On Core Code (Remove when not using any add-on&apos;s)*/
        ///.qmfv{visibility:visible !important;}.qmfh{visibility:hidden !important;}
        ///
        ////*!!!!!!!!!!! QuickMenu Core CSS [Do Not Modify!] !!!!!!!!!!!!!*/
        ///.qmclear {font-size:1px;height:0px;width:0px;clear:left;line-height:0px;display:block;}.qmmc {position:relative;}.qmmc a {float:left;display:block;white-space:nowrap;}.qmmc div a {float:none;}.qmsh div a{float:left;}.qmmc div {visibility:hidden;position:absolute;}
        ///
        ///
        ////*!!!!!!!!!!! QuickMenu Sty [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tree_Menu {
            get {
                return ResourceManager.GetString("Tree_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 var qm_si,qm_li,qm_lo,qm_tt,qm_th,qm_ts;var qp=&quot;parentNode&quot;;var qc=&quot;className&quot;;var qm_t=navigator.userAgent;var qm_o=qm_t.indexOf(&quot;Opera&quot;)+1;var qm_s=qm_t.indexOf(&quot;afari&quot;)+1;var qm_s2=qm_s&amp;&amp;window.XMLHttpRequest;var qm_n=qm_t.indexOf(&quot;Netscape&quot;)+1;var qm_v=parseFloat(navigator.vendorSub);if(window.showHelp)document.write(&quot;&lt;style type=&apos;text/css&apos;&gt;.qmclear{position:absolute;clear:none !important;}&lt;/style&gt;&quot;);;function qm_create(sd,v,ts,th,oc,rl,sh,fl,nf,l){var w=&quot;onmouseover&quot;;if(oc){w=&quot;onclick&quot;;th=0;ts=0;}if(!l [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Tree_Menu_Vertical {
            get {
                return ResourceManager.GetString("Tree_Menu_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head id=&quot;Head1&quot;&gt;&lt;title&gt;
        ///&lt;/title&gt;&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../css/Style.css&quot; /&gt;&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;form name=&quot;form1&quot; method=&quot;post&quot; id=&quot;form1&quot;&gt;
        ///&lt;div&gt;
        ///&lt;/div&gt;
        ///    &lt;div id=&quot;progress&quot;&gt;
        ///        &lt;span id=&quot;percent&quot;&gt;&lt;/span&gt;
        ///        &lt;div id=&quot;bar&quot;&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///    &lt;input id=&quot;isUploadFinished&quot; name=&quot;isUploadFin [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string UploadProgress {
            get {
                return ResourceManager.GetString("UploadProgress", resourceCulture);
            }
        }
    }
}
